# Generated by Django 4.2 on 2023-11-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_token',
            name='start_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
